In [6]:
import numpy as np

arr = np.random.randint(1, 11, size=100)
percentage = np.count_nonzero(arr > 7) / len(arr) * 100
print(f"Процент элементов вектора, больших 7: {percentage}%")

Процент элементов вектора, больших 7: 25.0%


In [2]:
import numpy as np

results = []
for _ in range(1000):
    arr = np.random.randint(1, 11, size=100)
    percentage = np.count_nonzero(arr > 7) / len(arr) * 100
    results.append(percentage)

equal_percent = len([x for x in results if x == 20])
percentage_equal = equal_percent / len(results) * 100
print(f"Часть результатов, равных 20%: {percentage_equal}%")

Часть результатов, равных 20%: 0.8999999999999999%


In [3]:
import numpy as np

matrix = np.tile(np.arange(1, 11), (10, 1))
print(matrix)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [4]:
import numpy as np

matrix = np.tile(np.arange(1, 11), (10, 1))
column_sums = np.sum(matrix, axis=0)
print(column_sums)

[ 10  20  30  40  50  60  70  80  90 100]
